// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/segmenter_data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "protocol/segmenter_data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mozc {
namespace converter {

namespace {

const ::google::protobuf::Descriptor* SegmenterDataSizeInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SegmenterDataSizeInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_protocol_2fsegmenter_5fdata_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_protocol_2fsegmenter_5fdata_2eproto() {
  protobuf_AddDesc_protocol_2fsegmenter_5fdata_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "protocol/segmenter_data.proto");
  GOOGLE_CHECK(file != NULL);
  SegmenterDataSizeInfo_descriptor_ = file->message_type(0);
  static const int SegmenterDataSizeInfo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SegmenterDataSizeInfo, compressed_lsize_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SegmenterDataSizeInfo, compressed_rsize_),
  };
  SegmenterDataSizeInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SegmenterDataSizeInfo_descriptor_,
      SegmenterDataSizeInfo::default_instance_,
      SegmenterDataSizeInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SegmenterDataSizeInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(SegmenterDataSizeInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SegmenterDataSizeInfo, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_protocol_2fsegmenter_5fdata_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SegmenterDataSizeInfo_descriptor_, &SegmenterDataSizeInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_protocol_2fsegmenter_5fdata_2eproto() {
  delete SegmenterDataSizeInfo::default_instance_;
  delete SegmenterDataSizeInfo_reflection_;
}

void protobuf_AddDesc_protocol_2fsegmenter_5fdata_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_protocol_2fsegmenter_5fdata_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035protocol/segmenter_data.proto\022\016mozc.co"
    "nverter\"K\n\025SegmenterDataSizeInfo\022\030\n\020comp"
    "ressed_lsize\030\001 \001(\004\022\030\n\020compressed_rsize\030\002"
    " \001(\004", 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocol/segmenter_data.proto", &protobuf_RegisterTypes);
  SegmenterDataSizeInfo::default_instance_ = new SegmenterDataSizeInfo();
  SegmenterDataSizeInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_protocol_2fsegmenter_5fdata_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_protocol_2fsegmenter_5fdata_2eproto {
  StaticDescriptorInitializer_protocol_2fsegmenter_5fdata_2eproto() {
    protobuf_AddDesc_protocol_2fsegmenter_5fdata_2eproto();
  }
} static_descriptor_initializer_protocol_2fsegmenter_5fdata_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SegmenterDataSizeInfo::kCompressedLsizeFieldNumber;
const int SegmenterDataSizeInfo::kCompressedRsizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SegmenterDataSizeInfo::SegmenterDataSizeInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mozc.converter.SegmenterDataSizeInfo)
}

void SegmenterDataSizeInfo::InitAsDefaultInstance() {
}

SegmenterDataSizeInfo::SegmenterDataSizeInfo(const SegmenterDataSizeInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:mozc.converter.SegmenterDataSizeInfo)
}

void SegmenterDataSizeInfo::SharedCtor() {
  _cached_size_ = 0;
  compressed_lsize_ = GOOGLE_ULONGLONG(0);
  compressed_rsize_ = GOOGLE_ULONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SegmenterDataSizeInfo::~SegmenterDataSizeInfo() {
  // @@protoc_insertion_point(destructor:mozc.converter.SegmenterDataSizeInfo)
  SharedDtor();
}

void SegmenterDataSizeInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void SegmenterDataSizeInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SegmenterDataSizeInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SegmenterDataSizeInfo_descriptor_;
}

const SegmenterDataSizeInfo& SegmenterDataSizeInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_protocol_2fsegmenter_5fdata_2eproto();
  return *default_instance_;
}

SegmenterDataSizeInfo* SegmenterDataSizeInfo::default_instance_ = NULL;

SegmenterDataSizeInfo* SegmenterDataSizeInfo::New(::google::protobuf::Arena* arena) const {
  SegmenterDataSizeInfo* n = new SegmenterDataSizeInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SegmenterDataSizeInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:mozc.converter.SegmenterDataSizeInfo)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(SegmenterDataSizeInfo, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SegmenterDataSizeInfo*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(compressed_lsize_, compressed_rsize_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SegmenterDataSizeInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mozc.converter.SegmenterDataSizeInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint64 compressed_lsize = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &compressed_lsize_)));
          set_has_compressed_lsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_compressed_rsize;
        break;
      }

      // optional uint64 compressed_rsize = 2;
      case 2: {
        if (tag == 16) {
         parse_compressed_rsize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &compressed_rsize_)));
          set_has_compressed_rsize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mozc.converter.SegmenterDataSizeInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mozc.converter.SegmenterDataSizeInfo)
  return false;
#undef DO_
}

void SegmenterDataSizeInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mozc.converter.SegmenterDataSizeInfo)
  // optional uint64 compressed_lsize = 1;
  if (has_compressed_lsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->compressed_lsize(), output);
  }

  // optional uint64 compressed_rsize = 2;
  if (has_compressed_rsize()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->compressed_rsize(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:mozc.converter.SegmenterDataSizeInfo)
}

::google::protobuf::uint8* SegmenterDataSizeInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mozc.converter.SegmenterDataSizeInfo)
  // optional uint64 compressed_lsize = 1;
  if (has_compressed_lsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->compressed_lsize(), target);
  }

  // optional uint64 compressed_rsize = 2;
  if (has_compressed_rsize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->compressed_rsize(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mozc.converter.SegmenterDataSizeInfo)
  return target;
}

int SegmenterDataSizeInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:mozc.converter.SegmenterDataSizeInfo)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3u) {
    // optional uint64 compressed_lsize = 1;
    if (has_compressed_lsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->compressed_lsize());
    }

    // optional uint64 compressed_rsize = 2;
    if (has_compressed_rsize()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->compressed_rsize());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SegmenterDataSizeInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mozc.converter.SegmenterDataSizeInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SegmenterDataSizeInfo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SegmenterDataSizeInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mozc.converter.SegmenterDataSizeInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mozc.converter.SegmenterDataSizeInfo)
    MergeFrom(*source);
  }
}

void SegmenterDataSizeInfo::MergeFrom(const SegmenterDataSizeInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mozc.converter.SegmenterDataSizeInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_compressed_lsize()) {
      set_compressed_lsize(from.compressed_lsize());
    }
    if (from.has_compressed_rsize()) {
      set_compressed_rsize(from.compressed_rsize());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SegmenterDataSizeInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mozc.converter.SegmenterDataSizeInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SegmenterDataSizeInfo::CopyFrom(const SegmenterDataSizeInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mozc.converter.SegmenterDataSizeInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SegmenterDataSizeInfo::IsInitialized() const {

  return true;
}

void SegmenterDataSizeInfo::Swap(SegmenterDataSizeInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SegmenterDataSizeInfo::InternalSwap(SegmenterDataSizeInfo* other) {
  std::swap(compressed_lsize_, other->compressed_lsize_);
  std::swap(compressed_rsize_, other->compressed_rsize_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SegmenterDataSizeInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SegmenterDataSizeInfo_descriptor_;
  metadata.reflection = SegmenterDataSizeInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SegmenterDataSizeInfo

// optional uint64 compressed_lsize = 1;
bool SegmenterDataSizeInfo::has_compressed_lsize() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SegmenterDataSizeInfo::set_has_compressed_lsize() {
  _has_bits_[0] |= 0x00000001u;
}
void SegmenterDataSizeInfo::clear_has_compressed_lsize() {
  _has_bits_[0] &= ~0x00000001u;
}
void SegmenterDataSizeInfo::clear_compressed_lsize() {
  compressed_lsize_ = GOOGLE_ULONGLONG(0);
  clear_has_compressed_lsize();
}
 ::google::protobuf::uint64 SegmenterDataSizeInfo::compressed_lsize() const {
  // @@protoc_insertion_point(field_get:mozc.converter.SegmenterDataSizeInfo.compressed_lsize)
  return compressed_lsize_;
}
 void SegmenterDataSizeInfo::set_compressed_lsize(::google::protobuf::uint64 value) {
  set_has_compressed_lsize();
  compressed_lsize_ = value;
  // @@protoc_insertion_point(field_set:mozc.converter.SegmenterDataSizeInfo.compressed_lsize)
}

// optional uint64 compressed_rsize = 2;
bool SegmenterDataSizeInfo::has_compressed_rsize() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SegmenterDataSizeInfo::set_has_compressed_rsize() {
  _has_bits_[0] |= 0x00000002u;
}
void SegmenterDataSizeInfo::clear_has_compressed_rsize() {
  _has_bits_[0] &= ~0x00000002u;
}
void SegmenterDataSizeInfo::clear_compressed_rsize() {
  compressed_rsize_ = GOOGLE_ULONGLONG(0);
  clear_has_compressed_rsize();
}
 ::google::protobuf::uint64 SegmenterDataSizeInfo::compressed_rsize() const {
  // @@protoc_insertion_point(field_get:mozc.converter.SegmenterDataSizeInfo.compressed_rsize)
  return compressed_rsize_;
}
 void SegmenterDataSizeInfo::set_compressed_rsize(::google::protobuf::uint64 value) {
  set_has_compressed_rsize();
  compressed_rsize_ = value;
  // @@protoc_insertion_point(field_set:mozc.converter.SegmenterDataSizeInfo.compressed_rsize)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace converter
}  // namespace mozc

// @@protoc_insertion_point(global_scope)
